name: Build and Deploy (kubernetes)

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{secrets.CICD_PROJECT}}
  CICD_CLUSTER: github-actions-cicd
  CICD_ZONE: us-central1-c
  DEPLOYMENT_NAME: github-actions-cicd
  IMAGE: github-actions-gke-image
  TAG: 1.0.0
jobs:
  setup-build-publish-deploy:
    name: setup Build Publish Deploy´
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Setup Google Cloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3            
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{secrets.CICD_SA_KEY}}
        project_id: ${{secrets.CICD_PROJECT}}

    - name: configure Docker
      run: |-
        gcloud --quiet auth configure-docker
    - name: Get Credentials
      run: |-
        gcloud container clusters get-credentials "$CICD_CLUSTER" --zone "$CICD_ZONE"

    - name: Build Docker Image
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" -f ./WebApiSaludar/Dockerfile .
    - name: Publish Docker image 
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    
    - name: Deploy Image to cluster
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide


